id: P004138
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC341
  title: 'བཀོལ་བདེའི་ཟས་སྨན་ལག་ལེན་གསལ་བའི་མེ་ལོང་། '
  author: ''
  volumes:
    a3a2e6373177420ea0befccd34eb8bfb:
      image_group_id: I2PD17822
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
